title: Fast Goat ğŸ for Finite Groups
author:
  name: "@aidevnn"
baseurl: "/FastGoat" # the subpath of your site, e.g. /blog
url: "https::/aidenn.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: hacker
remote_theme: pages-themes/hacker@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
